fullnameOverride: monitoring
alertmanager:
  enabled: true
grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    storageClassName: standard
    size: 2Gi
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: mlrun
prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
