fullnameOverride: nuclio
controller:
  enabled: true
dashboard:
  enabled: true
  image:
    repository: mlrun/nuclio-dashboard
    tag: 1.17.6-local.1
    pullPolicy: IfNotPresent
  containerBuilderKind: kaniko
  ingress:
    enabled: false
  build:
    insecurePushRegistry: true
autoscaler:
  enabled: false
dlx:
  enabled: false
rbac:
  create: true
  crdAccessMode: namespaced
crd:
  create: true
registry:
  pushPullUrl: mlrun-registry.mlrun.svc.cluster.local:5000
platform:
  projectsLeader:
    kind: mlrun
    synchronizationInterval: 1m
    apiAddress: http://mlrun-api:8080/api
