apiVersion: v1
kind: ConfigMap
metadata:
  name: mlrun-platform-env
  namespace: mlrun
data:
  MLRUN_HTTPDB__PROJECTS__LEADER: mlrun
  MLRUN_HTTPDB__PROJECTS__FOLLOWERS: nuclio
  MLRUN_MPIJOB_CRD_VERSION: v1
  MLRUN_CE__MODE: full
  MLRUN_FEATURE_STORE__DEFAULT_TARGETS: parquet
  MLRUN_FEATURE_STORE__DATA_PREFIXES__DEFAULT: /home/jovyan/data/{project}/FeatureStore/{name}/{kind}
  MLRUN_FEATURE_STORE__DATA_PREFIXES__NOSQL: ''
  MLRUN_MODEL_ENDPOINT_MONITORING__STORE_PREFIXES__DEFAULT: /home/jovyan/data/{project}/model-endpoints/{kind}
  MLRUN_MODEL_ENDPOINT_MONITORING__STORE_PREFIXES__USER_SPACE: /home/jovyan/data/{project}/model-endpoints/{kind}
  MLRUN_MODEL_ENDPOINT_MONITORING__STORE_PREFIXES__MONITORING_APPLICATION: /home/jovyan/data/{project}/monitoring-apps/
  MLRUN_GRAFANA_URL: http://127.0.0.1:3000
  MLRUN_TELEMETRY__ENABLED: 'true'
  MLRUN_TELEMETRY__OTLP_ENDPOINT: mlrun-otel-collector.mlrun.svc.cluster.local:4317
  MLRUN_TELEMETRY__INSECURE: 'true'
  MLRUN_SPARK_APP_IMAGE: gcr.io/iguazio/spark-app
  AWS_ENDPOINT_URL_S3: http://minio-service.mlrun.svc.cluster.local:9000
  AWS_DEFAULT_REGION: us-east-1
  S3_NON_ANONYMOUS: 'True'
  MLRUN_SPARK_OPERATOR_VERSION: spark-3
  MLRUN_SPARK_APP_IMAGE_TAG: 3.5.6-scala2.12-java17-ubuntu-1
  PYTHONPATH: /home/jovyan/data/.mlrun-kfp1:/mlrun:/mlrun/server/py
